package lists

import (
	"bytes"
	"compress/gzip"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"sort"
)

// blocklistFS embeds the per-category blocklistproject domain lists and the
// manifest generated by `go run ./tools/gen-blocklists`. Each category is its
// own gzip so a build can drop the giants (malware ~16MB, porn ~5MB) with a
// build-tag variant of this file later; the runtime tolerates any subset that
// is actually present. Total embedded ~32MB gz for all 25 categories.
//
//go:embed blocklists/*.txt.gz blocklists/manifest.json
var blocklistFS embed.FS

// BlocklistManifest describes the embedded assets and the upstream commit they
// were built from. The updater version-gates blocklist refresh against Commit.
type BlocklistManifest struct {
	Commit     string              `json:"commit"`
	FetchedAt  string              `json:"fetchedAt"`
	Categories []BlocklistCategory `json:"categories"`
}

type BlocklistCategory struct {
	Name    string `json:"name"`
	Domains int    `json:"domains"`
	Bytes   int    `json:"bytes"`
}

// EmbeddedManifest parses the embedded manifest.json.
func EmbeddedManifest() (BlocklistManifest, error) {
	var m BlocklistManifest

	b, err := blocklistFS.ReadFile("blocklists/manifest.json")
	if err != nil {
		return m, fmt.Errorf("can't read embedded blocklist manifest: %w", err)
	}

	if err := json.Unmarshal(b, &m); err != nil {
		return m, fmt.Errorf("can't parse embedded blocklist manifest: %w", err)
	}

	return m, nil
}

// EmbeddedCommit returns the blocklistproject commit SHA the embedded assets
// were built from (the cold-start version floor).
func EmbeddedCommit() (string, error) {
	m, err := EmbeddedManifest()
	if err != nil {
		return "", err
	}

	return m.Commit, nil
}

// EmbeddedCategories returns the names of categories that are actually embedded
// in this build (manifest ∩ files present), sorted.
func EmbeddedCategories() ([]string, error) {
	m, err := EmbeddedManifest()
	if err != nil {
		return nil, err
	}

	out := make([]string, 0, len(m.Categories))
	for _, c := range m.Categories {
		if _, err := blocklistFS.Open("blocklists/" + c.Name + ".txt.gz"); err == nil {
			out = append(out, c.Name)
		}
	}
	sort.Strings(out)

	return out, nil
}

// OpenEmbeddedCategory returns a reader over the decompressed domain list for
// one category (one domain per line). Caller must Close it.
func OpenEmbeddedCategory(cat string) (io.ReadCloser, error) {
	b, err := blocklistFS.ReadFile("blocklists/" + cat + ".txt.gz")
	if err != nil {
		return nil, fmt.Errorf("no embedded blocklist for category %q: %w", cat, err)
	}

	gr, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		return nil, fmt.Errorf("can't open embedded blocklist %q: %w", cat, err)
	}

	return gr, nil
}
